### ISSUE TITLE
Allow split the diff process from the data transformer/processor

### ISSUE THREAD

**Issue by joskfg** [mawrkus/joey-the-differ#6]
Currently if you want to for example order a list before comparing it, you need to overload the `areEqual` to do both things or do it in advance out of the tool.

To improve this behaviour it would be great to split this two responsibilities in two separate features. It could be done in several ways, but one easy way could be adding a new step in the configuration for the transform/processor part. 

For example:
```
const options = {
  preprocessors: {
    starsCount: (source, target) => {source: source*100, target:target*100}
  },
  differs: {
    'starsCount': (source, target) => ({
      areEqual: source <= target,
      meta: {
        op: 'replace',
        reason: 'number of stars decreased',
        delta: target - source,
      },
    }),
  },
};
```

or inside the differ like we did until now, but splitting the steps to avoid to repeat the field regexp and have a better track about the transformations produced before the diff.

WDYT?

**Comment by mawrkus** [comment]
That seems to be a good idea, I'll have a look at it ASAP.
I'll go for the "preprocessors" option, which looks cleaner to me.

**Comment by mawrkus** [comment]
https://github.com/mawrkus/joey-the-differ/pull/8 ;)

**Comment by joskfg** [comment]
It looks pretty good. That will simplify a lot the differs, KISS.

**Comment by mawrkus** [comment]
https://github.com/mawrkus/joey-the-differ/pull/8 merged and v1.4.0 published.

**Comment by joskfg** [comment]
Thanks! Is there a docker image built?

**Comment by mawrkus** [comment]
For now no, as I'm focusing on the lib features. Feel free to open an issue to talk about it!
